import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Syed Social Site",
  description: "Generated By SyedIt",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-950 text-slate-50 ${inter.className}`}>
        <nav>
          <Navbar />
        </nav>
        <div className="container xl:px-4 md:px-2 mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
